// <auto-generated />
using System;
using DealerDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerDatabase.Data.Migrations
{
    [DbContext(typeof(DealerDbContext))]
    [Migration("20261002150614_ConsolidateDealerModel")]
    partial class ConsolidateDealerModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AvgDaysInStock")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AvgListedPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AvgSoldPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyNumber")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaBusinessType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaFrn")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaPermissions")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinanceLenders")
                        .HasColumnType("TEXT");

                    b.Property<string>("FranchiseMake")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GoogleRating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GoogleReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IcoPaymentTier")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcoRegistrationNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InventoryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegalName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketcheckDealerId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MarketcheckLastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("OffersFinance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredAddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredAddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredCounty")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredPostcode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredTown")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentativeApr")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SafExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafMemberId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SicCodes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SoldLast30Days")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StockFeedProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TrustpilotScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleTypes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteDomain")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsitePlatform")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyNumber")
                        .IsUnique();

                    b.HasIndex("FcaFrn")
                        .IsUnique();

                    b.HasIndex("IcoRegistrationNumber")
                        .IsUnique();

                    b.HasIndex("MarketcheckDealerId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("Postcode");

                    b.HasIndex("SafMemberId")
                        .IsUnique();

                    b.HasIndex("VatNumber")
                        .IsUnique();

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRecordKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("SourceName", "SourceRecordKey")
                        .IsUnique();

                    b.ToTable("DealerSourceLinks");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSourceLink", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("SourceLinks")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Navigation("SourceLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
